galaxy-future/bridgx

cmd/scheduler/monitors/order.go
internal/model/base.go
internal/model/cluster.go
internal/service/order.go
tests/aliyun_test.go

不同region的阿里云cli返回的订单详情相同;忽略duplicate报错

不同region的阿里云cli返回的订单详情相同;忽略duplicate报错

---

pkg/cloud/aliyun/aliyun.go

style(region):获取完整的 region 中文名称

---

internal/service/account.go
internal/service/instance.go
internal/service/network.go
pkg/cloud/huaweiyun/ecs.go
tests/huaweiyun_test.go

新增 refresh instance type cache 的任务, 重试 5 次

feature(task):新增 refresh instance type cache 的任务, 重试 5 次

---

Makefile
docker-compose.yml
run-for-linux.sh
run-for-mac.sh

是否已 rebase dev 分支 (通过)
是否已执行 make format & make build (通过)
是否已在测试环境验证通过 (通过)

add docker-hub-all makefile, fix run-for-linux.sh

---

cmd/api/handler/instance.go

if not provider no return, add return.

add return

---

cmd/api/handler/cluster.go
cmd/api/handler/image.go
cmd/api/middleware/init.go
cmd/api/middleware/validation/custom_validator.go
cmd/api/middleware/validation/validator_test.go
cmd/api/request/types.go
internal/types/cluster.go

Feature lys validation api

---

cmd/api/handler/cluster.go
cmd/api/helper/cluster.go
cmd/api/helper/instance.go
internal/service/instance.go

feature(instance/describe_all):x核xG

---

cmd/api/handler/network.go
cmd/api/handler/organization.go
cmd/api/request/types.go
init/mysql/default.sql

feature(org):only admin can edit org name

---

README.md
cmd/api/handler/image.go
cmd/api/request/types.go
go.mod
go.sum
internal/service/instance.go

refactor(instance_type):use errgroup.reduced time from 1m30s to 30s

---

conf/config.yml
config/config.go
internal/model/account.go
pkg/encrypt/aes.go

feature(account):ak+salt as AES key

---

cmd/api/handler/instance.go

fix(instance):fix bug on  sql query

---

internal/service/cluster.go
internal/types/cluster.go

feature(cluster):memory & core

---

.github/pull_request_template.md

template(pr)

---

cmd/api/handler/gf-cluster/cluster/bridgx.go
cmd/api/handler/gf-cluster/cluster/cluster.go
cmd/api/handler/gf-cluster/instance/group.go
cmd/api/handler/gf-cluster/instance/instance.go
cmd/api/handler/gf-cluster/kubernetes/kubernetes.go
cmd/api/helper/gf_cluster.go
internal/clients/bridgx.go

整合代码，request取消json.marshal, 使用cast转换

---

cmd/api/handler/gf-cluster/instance/group.go
cmd/api/middleware/validation/custom_validator.go
pkg/gf-cluster/eci.go

-  added interface parameter validation

feat(k8s): added interface parameter validation

---

internal/gf-cluster/cluster-builder/cluster_init.go
internal/gf-cluster/cluster-builder/command.go

add machine function

---

cmd/api/request/types.go

modify password bind request param

---

internal/service/cluster.go
pkg/cloud/model.go

- [ add check outer ip if need]

add check outer ip if need

---

Makefile
run-for-linux.sh
run-for-mac.sh

Feature quickstart install mysql etcd interactive

---

cmd/api/handler/instance.go
cmd/api/helper/instance.go
cmd/api/response/response.go
internal/constants/cluster.go
internal/service/instance.go

Feature add gpu computing power

---

cmd/api/handler/cluster.go
cmd/api/request/types.go
cmd/api/response/response.go
cmd/api/routers/router.go
internal/model/machine.go
internal/service/cluster.go
pkg/utils/ssh.go
pkg/utils/ssh_test.go

- Added machine connectivity detection

feat: Added machine connectivity detection

---

cmd/api/handler/cluster.go
cmd/api/handler/operation_log.go
cmd/api/routers/router.go
init/mysql/default.sql
internal/errs/err.go
internal/model/account.go
internal/model/log.go
internal/model/user.go
internal/service/cluster.go
internal/service/operation_log.go
internal/service/user.go
pkg/cmp/diff.go
pkg/cmp/diff_test.go
pkg/utils/time.go
tests/operation_log_test.go

feature(log):diff

---

init/mysql/default.sql

fix semicolon error

---

cmd/api/handler/network.go
cmd/api/request/types.go
internal/model/network.go
internal/service/network.go

fix(vpc):ak

---

internal/gf-cluster/cluster-builder/tmpl.go

add iptables set

---

cmd/scheduler/scheduler.go

disable cleaner

---

cmd/api/handler/cluster.go
cmd/api/handler/instance.go
cmd/scheduler/monitors/order.go
init/mysql/default.sql
internal/constants/cluster.go
internal/model/instance.go
internal/model/user.go
internal/pool/executor.go
internal/service/cloud.go
internal/service/cluster.go
pkg/cloud/alibaba/api.go
pkg/cloud/huawei/api.go
pkg/cloud/huawei/constants.go
pkg/cloud/huawei/ecs.go
pkg/cloud/huawei/securitygroup.go
pkg/cloud/model.go
tests/alibaba_cloud_test.go
tests/huawei_cloud_test.go
tests/instance_test.go
tests/network_test.go

- [yes] rebase origin/dev branch (**passed**)
- [yes] make format & make build  (**passed**)
- [yes] union test or test in dev env(**passed**)

get ExpireAt;GetInstances -> GetInstanceByTag

---

Makefile
tests/network_test.go

fix go vet test

---

run-for-mac.sh

- [] rebase origin/dev branch (**passed**)

fix mac m1 install warning note

---

cmd/api/handler/gf-cluster/cluster/cluster.go
cmd/api/handler/gf-cluster/route.go
internal/model/install_step.go
pkg/gf-cluster/kubernetes_install_step.go

K8s install log

---

internal/gf-cluster/cluster-builder/command.go

增加重启kubelet && 删除node节点接口

---

cmd/api/handler/gf-cluster/cluster/cluster.go
pkg/cloud/alibaba/api.go
pkg/cloud/huawei/api.go
pkg/cloud/model.go

add image name

---

init/mysql/default.sql

feat(sql):remove text default value

---

internal/service/network.go

fix create time parse error

---

cmd/api/handler/organization.go
cmd/api/handler/user.go
cmd/api/helper/organization.go
cmd/api/helper/user.go
cmd/api/middleware/authorization/user_token.go
cmd/api/request/types.go
cmd/api/response/base.go
cmd/api/response/response.go
cmd/api/routers/router.go
init/mysql/default.sql
internal/constants/user.go
internal/model/user.go
internal/service/user.go

mico permission

---

internal/errs/err.go
internal/service/operation_log.go
pkg/cmp/diff.go
pkg/cmp/diff_test.go

Fix lys diff

---

cmd/api/helper/task.go
internal/model/instance.go
internal/model/network.go
internal/pool/executor.go
internal/service/cloud.go
internal/service/cluster.go
pkg/cloud/alibaba/api.go
pkg/cloud/huawei/ecs.go
pkg/cloud/tencent/ecs.go
pkg/utils/slice.go
tests/cloud_test.go

- [yes] rebase origin/dev branch (**passed**)
- [yes] make format & make build  (**passed**)
- [yes] union test or test in dev env(**passed**)

fix expansion and reduction of capacity

---

cmd/api/helper/cluster.go
cmd/api/response/response.go
internal/model/network.go

clusterlist add cputype

---

cmd/api/handler/cluster.go
cmd/api/request/types.go
init/mysql/default.sql
internal/model/cluster_tag.go
internal/service/cluster_tag.go
internal/service/network.go
tests/network_test.go

add tag desc

---

cmd/api/middleware/validation/custom_validator.go
go.mod
go.sum
internal/logs/logger.go
internal/model/network.go
internal/service/account.go
internal/service/cloud.go
internal/service/network.go
pkg/cloud/baidu/api.go
pkg/cloud/baidu/api_test.go
pkg/cloud/baidu/constants.go
pkg/cloud/constants.go
pkg/utils/slice.go
tests/cloud_account_test.go
tests/cluster_test.go
tests/conf/config.yml
tests/instance_test.go
tests/main_test.go
tests/network_test.go
tests/region_test.go
tests/securityGroup_test.go
tests/subnet_test.go
tests/vpc_test.go

Feature baiducloud

---

cmd/api/middleware/validation/custom_validator.go
docs/developer_api.md
docs/en-developer-api.md
internal/service/account.go
internal/service/cloud.go
internal/service/network.go
pkg/cloud/aws/api.go
pkg/cloud/aws/ecs.go
pkg/cloud/aws/ecs_test.go
pkg/cloud/aws/securitygroup.go
pkg/cloud/aws/vpc.go
pkg/cloud/constants.go
tests/cloud_account_test.go
tests/cluster_test.go
tests/main_test.go
tests/region_test.go
tests/securityGroup_test.go
tests/subnet_test.go
tests/vpc_test.go

Spelling improved

---

pkg/cloud/baidu/api.go

Support BCC instance login use keypair

---

go.mod
go.sum
pkg/cloud/tencent/api.go
pkg/cloud/tencent/s3.go
pkg/cloud/tencent/s3_test.go

- [1] 完成三个接口 
* ListObjects(endpoint, bucketName, prefix string) ([]ObjectProperties, error)
腾讯云 endpoint 格式为："https://examplebucket-1250000000.cos.ap-guangzhou.myqcloud.com"；其中就包含了 bucketName ，所以 该接口 bucketName 参数为多余的。
* ListBucket(endpoint string) ([]BucketProperties, error)
同理 本接口 bucketName 参数也是多余的
* GetObjectDownloadUrl(bucketName, objectKey string) (string, error)
获取 Object 光有 bucketName 不够，还需要 region ，所以这里的 bucketName 改成了 endpoint
- [2] 一个接口腾讯官方文档无接口
- GetOssDownloadUrl(string, string, string) string

bridgx-20221017 任务 之 腾讯云S3 特性

---

go.mod
go.sum
pkg/cloud/tencent/api.go
pkg/cloud/tencent/constants.go
pkg/cloud/tencent/cr.go
pkg/cloud/tencent/cr_test.go

- [1] 
EnterpriseImageList 获取企业版容器镜像信息列表
PersonalImageList 获取个人版容器镜像信息列表 接口实现方法一样
- [2]
结构体  定义有问题 
`type Repository struct {
Name string `json:"name"`
ID   string `json:"id"`
}`
官方文档中仓库没有 ID 属性  [参考](https://cloud.tencent.com/document/api/1141/41603#RepoInfo)

[Task][TencentCloud] Support TCR Operation #197

---

go.mod
go.sum
pkg/cloud/ecloud/s3.go
pkg/cloud/ecloud/s3_test.go

- [1] GetOssDownloadUrl  官方文档好像没有这个接口
- [2] GetObjectDownloadUrl 这个接口是按照 aws 的接口来

[Task][移动云]Support S3 Operation #210

---

pkg/cloud/ecloud/README.md

docs(ecloud):readme.md
